# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tablero.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1453, 1272)
        MainWindow.setStyleSheet("background-color: #ADD8E6")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(330, -10, 821, 751))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.finalVerde7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalVerde7.setStyleSheet("background-color: green;\n"
                                       "border: 1px solid black;")
        self.finalVerde7.setText("")
        self.finalVerde7.setObjectName("finalVerde7")
        self.gridLayout.addWidget(self.finalVerde7, 11, 9, 1, 1)
        self.casilla53 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla53.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla53.setObjectName("casilla53")
        self.gridLayout.addWidget(self.casilla53, 24, 10, 1, 1)
        self.casilla37 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla37.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla37.setObjectName("casilla37")
        self.gridLayout.addWidget(self.casilla37, 11, 2, 1, 1)
        self.casilla10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla10.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla10.setObjectName("casilla10")
        self.gridLayout.addWidget(self.casilla10, 7, 10, 1, 1)
        self.casilla58 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla58.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla58.setObjectName("casilla58")
        self.gridLayout.addWidget(self.casilla58, 19, 10, 1, 1)
        self.casilla51 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla51.setStyleSheet("background-color: grey;\n"
                                     "border: 1px solid black;")
        self.casilla51.setObjectName("casilla51")
        self.gridLayout.addWidget(self.casilla51, 25, 9, 1, 1)
        self.casilla28 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla28.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla28.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla28.setObjectName("casilla28")
        self.gridLayout.addWidget(self.casilla28, 9, 5, 1, 1)
        self.casilla44 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla44.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla44.setObjectName("casilla44")
        self.gridLayout.addWidget(self.casilla44, 19, 8, 1, 1)
        self.casilla49 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla49.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla49.setObjectName("casilla49")
        self.gridLayout.addWidget(self.casilla49, 24, 8, 1, 1)
        self.casilla54 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla54.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla54.setObjectName("casilla54")
        self.gridLayout.addWidget(self.casilla54, 23, 10, 1, 1)
        self.casilla46 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla46.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla46.setObjectName("casilla46")
        self.gridLayout.addWidget(self.casilla46, 21, 8, 1, 1)
        self.casilla27 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla27.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla27.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla27.setObjectName("casilla27")
        self.gridLayout.addWidget(self.casilla27, 9, 6, 1, 1)
        self.casilla30 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla30.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla30.setStyleSheet("background-color: grey;\n"
                                     "border: 1px solid black;")
        self.casilla30.setObjectName("casilla30")
        self.gridLayout.addWidget(self.casilla30, 9, 3, 1, 1)
        self.casilla36 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla36.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla36.setObjectName("casilla36")
        self.gridLayout.addWidget(self.casilla36, 11, 1, 1, 1)
        self.casilla40 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla40.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla40.setObjectName("casilla40")
        self.gridLayout.addWidget(self.casilla40, 11, 5, 1, 1)
        self.casilla56 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla56.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla56.setObjectName("casilla56")
        self.gridLayout.addWidget(self.casilla56, 21, 10, 1, 1)
        self.casilla55 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla55.setStyleSheet("background-color: green;\n"
                                     "border: 1px solid black;")
        self.casilla55.setObjectName("casilla55")
        self.gridLayout.addWidget(self.casilla55, 22, 10, 1, 1)
        self.casilla47 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla47.setStyleSheet("background-color: grey;\n"
                                     "border: 1px solid black;")
        self.casilla47.setObjectName("casilla47")
        self.gridLayout.addWidget(self.casilla47, 22, 8, 1, 1)
        self.casilla45 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla45.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla45.setObjectName("casilla45")
        self.gridLayout.addWidget(self.casilla45, 20, 8, 1, 1)
        self.casilla19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla19.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla19.setObjectName("casilla19")
        self.gridLayout.addWidget(self.casilla19, 2, 8, 1, 1)
        self.casilla33 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla33.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla33.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla33.setObjectName("casilla33")
        self.gridLayout.addWidget(self.casilla33, 9, 0, 1, 1)
        self.casilla2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla2.setStyleSheet("background-color: white;\n"
                                    "border: 1px solid black;\n"
                                    "color: black;")
        self.casilla2.setObjectName("casilla2")
        self.gridLayout.addWidget(self.casilla2, 9, 17, 1, 1)
        self.casilla43 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla43.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla43.setObjectName("casilla43")
        self.gridLayout.addWidget(self.casilla43, 11, 8, 1, 1)
        self.casilla62 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla62.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla62.setObjectName("casilla62")
        self.gridLayout.addWidget(self.casilla62, 11, 13, 1, 1)
        self.casilla25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla25.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla25.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla25.setObjectName("casilla25")
        self.gridLayout.addWidget(self.casilla25, 9, 8, 1, 1)
        self.casilla18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla18.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla18.setObjectName("casilla18")
        self.gridLayout.addWidget(self.casilla18, 1, 8, 1, 1)
        self.casilla9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla9.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla9.setStyleSheet("background-color: white;\n"
                                    "border: 1px solid black;\n"
                                    "color: black;")
        self.casilla9.setObjectName("casilla9")
        self.gridLayout.addWidget(self.casilla9, 9, 10, 1, 1)
        self.casilla14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla14.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla14.setObjectName("casilla14")
        self.gridLayout.addWidget(self.casilla14, 3, 10, 1, 1)
        self.casilla3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla3.setStyleSheet("background-color: white;\n"
                                    "border: 1px solid black;\n"
                                    "color: black;")
        self.casilla3.setObjectName("casilla3")
        self.gridLayout.addWidget(self.casilla3, 9, 16, 1, 1)
        self.casilla68 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla68.setStyleSheet("background-color: grey;\n"
                                     "border: 1px solid black;")
        self.casilla68.setObjectName("casilla68")
        self.gridLayout.addWidget(self.casilla68, 10, 18, 1, 1)
        self.casilla4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla4.setStyleSheet("background-color: yellow;\n"
                                    "border: 1px solid black;\n"
                                    "color: black;")
        self.casilla4.setObjectName("casilla4")
        self.gridLayout.addWidget(self.casilla4, 9, 15, 1, 1)
        self.casilla8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla8.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla8.setStyleSheet("background-color: white;\n"
                                    "border: 1px solid black;\n"
                                    "color: black;")
        self.casilla8.setObjectName("casilla8")
        self.gridLayout.addWidget(self.casilla8, 9, 11, 1, 1)
        self.casilla20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla20.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla20.setObjectName("casilla20")
        self.gridLayout.addWidget(self.casilla20, 3, 8, 1, 1)
        self.casilla11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla11.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla11.setObjectName("casilla11")
        self.gridLayout.addWidget(self.casilla11, 6, 10, 1, 1)
        self.llagada = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.llagada.setMinimumSize(QtCore.QSize(30, 30))
        self.llagada.setStyleSheet("border: none;")
        self.llagada.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagenes/llegada.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.llagada.setIcon(icon)
        self.llagada.setIconSize(QtCore.QSize(50, 50))
        self.llagada.setObjectName("llagada")
        self.gridLayout.addWidget(self.llagada, 10, 9, 1, 1)
        self.casaAmarillo = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casaAmarillo.setStyleSheet("border: none;")
        self.casaAmarillo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagenes/casillaAmarillo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.casaAmarillo.setIcon(icon1)
        self.casaAmarillo.setIconSize(QtCore.QSize(300, 300))
        self.casaAmarillo.setObjectName("casaAmarillo")
        self.gridLayout.addWidget(self.casaAmarillo, 1, 12, 7, 7)
        self.casaVerde = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casaVerde.setStyleSheet("border: none;")
        self.casaVerde.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagenes/casillaVerde.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.casaVerde.setIcon(icon2)
        self.casaVerde.setIconSize(QtCore.QSize(300, 300))
        self.casaVerde.setObjectName("casaVerde")
        self.gridLayout.addWidget(self.casaVerde, 19, 12, 7, 7)
        self.casaRoja = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casaRoja.setStyleSheet("border: none;")
        self.casaRoja.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagenes/casillaRoja.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.casaRoja.setIcon(icon3)
        self.casaRoja.setIconSize(QtCore.QSize(300, 300))
        self.casaRoja.setObjectName("casaRoja")
        self.gridLayout.addWidget(self.casaRoja, 19, 0, 7, 7)
        self.casilla32 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla32.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla32.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla32.setObjectName("casilla32")
        self.gridLayout.addWidget(self.casilla32, 9, 1, 1, 1)
        self.casilla41 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla41.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla41.setObjectName("casilla41")
        self.gridLayout.addWidget(self.casilla41, 11, 6, 1, 1)
        self.casilla63 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla63.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla63.setObjectName("casilla63")
        self.gridLayout.addWidget(self.casilla63, 11, 14, 1, 1)
        self.casilla67 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla67.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla67.setObjectName("casilla67")
        self.gridLayout.addWidget(self.casilla67, 11, 18, 1, 1)
        self.casilla35 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla35.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla35.setObjectName("casilla35")
        self.gridLayout.addWidget(self.casilla35, 11, 0, 1, 1)
        self.casilla23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla23.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla23.setObjectName("casilla23")
        self.gridLayout.addWidget(self.casilla23, 6, 8, 1, 1)
        self.casilla57 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla57.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla57.setObjectName("casilla57")
        self.gridLayout.addWidget(self.casilla57, 20, 10, 1, 1)
        self.casilla29 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla29.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla29.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla29.setObjectName("casilla29")
        self.gridLayout.addWidget(self.casilla29, 9, 4, 1, 1)
        self.casilla52 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla52.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla52.setObjectName("casilla52")
        self.gridLayout.addWidget(self.casilla52, 25, 10, 1, 1)
        self.finalAzul1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAzul1.setStyleSheet("background-color: blue;\n"
                                      "border: 1px solid black;")
        self.finalAzul1.setText("")
        self.finalAzul1.setObjectName("finalAzul1")
        self.gridLayout.addWidget(self.finalAzul1, 2, 9, 1, 1)
        self.finalAzul2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAzul2.setStyleSheet("background-color: blue;\n"
                                      "border: 1px solid black;")
        self.finalAzul2.setText("")
        self.finalAzul2.setObjectName("finalAzul2")
        self.gridLayout.addWidget(self.finalAzul2, 3, 9, 1, 1)
        self.finalAzul5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAzul5.setStyleSheet("background-color: blue;\n"
                                      "border: 1px solid black;")
        self.finalAzul5.setText("")
        self.finalAzul5.setObjectName("finalAzul5")
        self.gridLayout.addWidget(self.finalAzul5, 6, 9, 1, 1)
        self.finalAzul3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAzul3.setStyleSheet("background-color: blue;\n"
                                      "border: 1px solid black;")
        self.finalAzul3.setText("")
        self.finalAzul3.setObjectName("finalAzul3")
        self.gridLayout.addWidget(self.finalAzul3, 4, 9, 1, 1)
        self.finalAzul4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAzul4.setStyleSheet("background-color: blue;\n"
                                      "border: 1px solid black;")
        self.finalAzul4.setText("")
        self.finalAzul4.setObjectName("finalAzul4")
        self.gridLayout.addWidget(self.finalAzul4, 5, 9, 1, 1)
        self.finalAzul6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAzul6.setStyleSheet("background-color: blue;\n"
                                      "border: 1px solid black;")
        self.finalAzul6.setText("")
        self.finalAzul6.setObjectName("finalAzul6")
        self.gridLayout.addWidget(self.finalAzul6, 7, 9, 1, 1)
        self.finalAzul7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAzul7.setMinimumSize(QtCore.QSize(30, 0))
        self.finalAzul7.setStyleSheet("background-color: blue;\n"
                                      "border: 1px solid black;")
        self.finalAzul7.setText("")
        self.finalAzul7.setObjectName("finalAzul7")
        self.gridLayout.addWidget(self.finalAzul7, 9, 9, 1, 1)
        self.finalRoja2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalRoja2.setStyleSheet("background-color: red;\n"
                                      "border: 1px solid black;")
        self.finalRoja2.setText("")
        self.finalRoja2.setObjectName("finalRoja2")
        self.gridLayout.addWidget(self.finalRoja2, 10, 2, 1, 1)
        self.finalRoja1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalRoja1.setStyleSheet("background-color: red;\n"
                                      "border: 1px solid black;")
        self.finalRoja1.setText("")
        self.finalRoja1.setObjectName("finalRoja1")
        self.gridLayout.addWidget(self.finalRoja1, 10, 1, 1, 1)
        self.finalRoja3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalRoja3.setStyleSheet("background-color: red;\n"
                                      "border: 1px solid black;")
        self.finalRoja3.setText("")
        self.finalRoja3.setObjectName("finalRoja3")
        self.gridLayout.addWidget(self.finalRoja3, 10, 3, 1, 1)
        self.finalRoja4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalRoja4.setStyleSheet("background-color: red;\n"
                                      "border: 1px solid black;")
        self.finalRoja4.setText("")
        self.finalRoja4.setObjectName("finalRoja4")
        self.gridLayout.addWidget(self.finalRoja4, 10, 4, 1, 1)
        self.finalRoja5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalRoja5.setStyleSheet("background-color: red;\n"
                                      "border: 1px solid black;")
        self.finalRoja5.setText("")
        self.finalRoja5.setObjectName("finalRoja5")
        self.gridLayout.addWidget(self.finalRoja5, 10, 5, 1, 1)
        self.finalRoja6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalRoja6.setStyleSheet("background-color: red;\n"
                                      "border: 1px solid black;")
        self.finalRoja6.setText("")
        self.finalRoja6.setObjectName("finalRoja6")
        self.gridLayout.addWidget(self.finalRoja6, 10, 6, 1, 1)
        self.finalRoja7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalRoja7.setStyleSheet("background-color: red;\n"
                                      "border: 1px solid black;")
        self.finalRoja7.setText("")
        self.finalRoja7.setObjectName("finalRoja7")
        self.gridLayout.addWidget(self.finalRoja7, 10, 7, 1, 1)
        self.finalAmarillo1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAmarillo1.setStyleSheet("background-color: yellow;\n"
                                          "border: 1px solid black;")
        self.finalAmarillo1.setText("")
        self.finalAmarillo1.setObjectName("finalAmarillo1")
        self.gridLayout.addWidget(self.finalAmarillo1, 10, 17, 1, 1)
        self.finalAmarillo2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAmarillo2.setStyleSheet("background-color: yellow;\n"
                                          "border: 1px solid black;")
        self.finalAmarillo2.setText("")
        self.finalAmarillo2.setObjectName("finalAmarillo2")
        self.gridLayout.addWidget(self.finalAmarillo2, 10, 16, 1, 1)
        self.finalAmarillo3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAmarillo3.setStyleSheet("background-color: yellow;\n"
                                          "border: 1px solid black;")
        self.finalAmarillo3.setText("")
        self.finalAmarillo3.setObjectName("finalAmarillo3")
        self.gridLayout.addWidget(self.finalAmarillo3, 10, 15, 1, 1)
        self.finalAmarillo5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAmarillo5.setStyleSheet("background-color: yellow;\n"
                                          "border: 1px solid black;")
        self.finalAmarillo5.setText("")
        self.finalAmarillo5.setObjectName("finalAmarillo5")
        self.gridLayout.addWidget(self.finalAmarillo5, 10, 13, 1, 1)
        self.finalAmarillo6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAmarillo6.setStyleSheet("background-color: yellow;\n"
                                          "border: 1px solid black;")
        self.finalAmarillo6.setText("")
        self.finalAmarillo6.setObjectName("finalAmarillo6")
        self.gridLayout.addWidget(self.finalAmarillo6, 10, 12, 1, 1)
        self.finalAmarillo7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAmarillo7.setStyleSheet("background-color: yellow;\n"
                                          "border: 1px solid black;")
        self.finalAmarillo7.setText("")
        self.finalAmarillo7.setObjectName("finalAmarillo7")
        self.gridLayout.addWidget(self.finalAmarillo7, 10, 11, 1, 1)
        self.finalVerde5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalVerde5.setStyleSheet("background-color: green;\n"
                                       "border: 1px solid black;")
        self.finalVerde5.setText("")
        self.finalVerde5.setObjectName("finalVerde5")
        self.gridLayout.addWidget(self.finalVerde5, 20, 9, 1, 1)
        self.finalVerde4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalVerde4.setStyleSheet("background-color: green;\n"
                                       "border: 1px solid black;")
        self.finalVerde4.setText("")
        self.finalVerde4.setObjectName("finalVerde4")
        self.gridLayout.addWidget(self.finalVerde4, 21, 9, 1, 1)
        self.finalVerde3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalVerde3.setStyleSheet("background-color: green;\n"
                                       "border: 1px solid black;")
        self.finalVerde3.setText("")
        self.finalVerde3.setObjectName("finalVerde3")
        self.gridLayout.addWidget(self.finalVerde3, 22, 9, 1, 1)
        self.finalVerde2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalVerde2.setStyleSheet("background-color: green;\n"
                                       "border: 1px solid black;")
        self.finalVerde2.setText("")
        self.finalVerde2.setObjectName("finalVerde2")
        self.gridLayout.addWidget(self.finalVerde2, 23, 9, 1, 1)
        self.finalVerde1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalVerde1.setStyleSheet("background-color: green;\n"
                                       "border: 1px solid black;")
        self.finalVerde1.setText("")
        self.finalVerde1.setObjectName("finalVerde1")
        self.gridLayout.addWidget(self.finalVerde1, 24, 9, 1, 1)
        self.casilla17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla17.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla17.setStyleSheet("background-color: grey;\n"
                                     "border: 1px solid black;")
        self.casilla17.setObjectName("casilla17")
        self.gridLayout.addWidget(self.casilla17, 1, 9, 1, 1)
        self.finalAmarillo4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalAmarillo4.setStyleSheet("background-color: yellow;\n"
                                          "border: 1px solid black;")
        self.finalAmarillo4.setText("")
        self.finalAmarillo4.setObjectName("finalAmarillo4")
        self.gridLayout.addWidget(self.finalAmarillo4, 10, 14, 1, 1)
        self.finalVerde6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.finalVerde6.setStyleSheet("background-color: green;\n"
                                       "border: 1px solid black;")
        self.finalVerde6.setText("")
        self.finalVerde6.setObjectName("finalVerde6")
        self.gridLayout.addWidget(self.finalVerde6, 19, 9, 1, 1)
        self.casilla15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla15.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla15.setObjectName("casilla15")
        self.gridLayout.addWidget(self.casilla15, 2, 10, 1, 1)
        self.casilla21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla21.setStyleSheet("background-color: blue;\n"
                                     "border: 1px solid black;")
        self.casilla21.setObjectName("casilla21")
        self.gridLayout.addWidget(self.casilla21, 4, 8, 1, 1)
        self.casilla22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla22.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla22.setObjectName("casilla22")
        self.gridLayout.addWidget(self.casilla22, 5, 8, 1, 1)
        self.casilla5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla5.setStyleSheet("background-color: white;\n"
                                    "border: 1px solid black;\n"
                                    "color: black;")
        self.casilla5.setObjectName("casilla5")
        self.gridLayout.addWidget(self.casilla5, 9, 14, 1, 1)
        self.casilla1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla1.setStyleSheet("background-color: white;\n"
                                    "border: 1px solid black;\n"
                                    "color: black;")
        self.casilla1.setObjectName("casilla1")
        self.gridLayout.addWidget(self.casilla1, 9, 18, 1, 1)
        self.casilla13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla13.setStyleSheet("background-color: grey;\n"
                                     "border: 1px solid black;")
        self.casilla13.setObjectName("casilla13")
        self.gridLayout.addWidget(self.casilla13, 4, 10, 1, 1)
        self.casilla12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla12.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla12.setObjectName("casilla12")
        self.gridLayout.addWidget(self.casilla12, 5, 10, 1, 1)
        self.casilla24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla24.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla24.setObjectName("casilla24")
        self.gridLayout.addWidget(self.casilla24, 7, 8, 1, 1)
        self.casilla7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla7.setStyleSheet("background-color: white;\n"
                                    "border: 1px solid black;\n"
                                    "color: black;")
        self.casilla7.setObjectName("casilla7")
        self.gridLayout.addWidget(self.casilla7, 9, 12, 1, 1)
        self.casilla6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla6.setStyleSheet("background-color: white;\n"
                                    "border: 1px solid black;\n"
                                    "color: black;")
        self.casilla6.setObjectName("casilla6")
        self.gridLayout.addWidget(self.casilla6, 9, 13, 1, 1)
        self.casilla64 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla64.setStyleSheet("background-color: grey;\n"
                                     "border: 1px solid black;")
        self.casilla64.setObjectName("casilla64")
        self.gridLayout.addWidget(self.casilla64, 11, 15, 1, 1)
        self.casilla61 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla61.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla61.setObjectName("casilla61")
        self.gridLayout.addWidget(self.casilla61, 11, 12, 1, 1)
        self.casilla60 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla60.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla60.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla60.setObjectName("casilla60")
        self.gridLayout.addWidget(self.casilla60, 11, 11, 1, 1)
        self.casilla66 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla66.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla66.setObjectName("casilla66")
        self.gridLayout.addWidget(self.casilla66, 11, 17, 1, 1)
        self.casilla65 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla65.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla65.setObjectName("casilla65")
        self.gridLayout.addWidget(self.casilla65, 11, 16, 1, 1)
        self.casilla16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla16.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla16.setObjectName("casilla16")
        self.gridLayout.addWidget(self.casilla16, 1, 10, 1, 1)
        self.casilla34 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla34.setStyleSheet("background-color: grey;\n"
                                     "border: 1px solid black;")
        self.casilla34.setObjectName("casilla34")
        self.gridLayout.addWidget(self.casilla34, 10, 0, 1, 1)
        self.casilla59 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla59.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla59.setObjectName("casilla59")
        self.gridLayout.addWidget(self.casilla59, 11, 10, 1, 1)
        self.casilla31 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla31.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla31.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla31.setObjectName("casilla31")
        self.gridLayout.addWidget(self.casilla31, 9, 2, 1, 1)
        self.casilla26 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla26.setEnabled(True)
        self.casilla26.setMinimumSize(QtCore.QSize(30, 0))
        self.casilla26.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla26.setObjectName("casilla26")
        self.gridLayout.addWidget(self.casilla26, 9, 7, 1, 1)
        self.casilla42 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla42.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla42.setObjectName("casilla42")
        self.gridLayout.addWidget(self.casilla42, 11, 7, 1, 1)
        self.casilla48 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla48.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla48.setObjectName("casilla48")
        self.gridLayout.addWidget(self.casilla48, 23, 8, 1, 1)
        self.casilla38 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla38.setStyleSheet("background-color: red;\n"
                                     "border: 1px solid black;")
        self.casilla38.setObjectName("casilla38")
        self.gridLayout.addWidget(self.casilla38, 11, 3, 1, 1)
        self.casilla50 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla50.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla50.setObjectName("casilla50")
        self.gridLayout.addWidget(self.casilla50, 25, 8, 1, 1)
        self.casilla39 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casilla39.setStyleSheet("background-color: white;\n"
                                     "border: 1px solid black;\n"
                                     "color: black;")
        self.casilla39.setObjectName("casilla39")
        self.gridLayout.addWidget(self.casilla39, 11, 4, 1, 1)
        self.casaAzul = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.casaAzul.setStyleSheet("border: none;")
        self.casaAzul.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("imagenes/casillaAzul.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.casaAzul.setIcon(icon4)
        self.casaAzul.setIconSize(QtCore.QSize(300, 300))
        self.casaAzul.setObjectName("casaAzul")
        self.gridLayout.addWidget(self.casaAzul, 1, 0, 7, 7)
        self.btnLanzarDado = QtWidgets.QPushButton(self.centralwidget)
        self.btnLanzarDado.setGeometry(QtCore.QRect(100, 60, 113, 32))
        self.btnLanzarDado.setStyleSheet("color: black;")
        self.btnLanzarDado.setObjectName("btnLanzarDado")
        self.labelResultadoDado = QtWidgets.QLabel(self.centralwidget)
        self.labelResultadoDado.setGeometry(QtCore.QRect(120, 110, 60, 16))
        self.labelResultadoDado.setStyleSheet("color: black;")
        self.labelResultadoDado.setText("")
        self.labelResultadoDado.setObjectName("labelResultadoDado")
        self.label_turno = QtWidgets.QLabel(self.centralwidget)
        self.label_turno.setGeometry(QtCore.QRect(160, 20, 141, 16))
        self.label_turno.setStyleSheet("color: black;")
        self.label_turno.setText("")
        self.label_turno.setObjectName("label_turno")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 60, 16))
        self.label.setStyleSheet("color: black;")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1453, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.casilla53.setText(_translate("MainWindow", "53"))
        self.casilla37.setText(_translate("MainWindow", "37"))
        self.casilla10.setText(_translate("MainWindow", "10"))
        self.casilla58.setText(_translate("MainWindow", "58"))
        self.casilla51.setText(_translate("MainWindow", "51"))
        self.casilla28.setText(_translate("MainWindow", "28"))
        self.casilla44.setText(_translate("MainWindow", "44"))
        self.casilla49.setText(_translate("MainWindow", "49"))
        self.casilla54.setText(_translate("MainWindow", "54"))
        self.casilla46.setText(_translate("MainWindow", "46"))
        self.casilla27.setText(_translate("MainWindow", "27"))
        self.casilla30.setText(_translate("MainWindow", "30"))
        self.casilla36.setText(_translate("MainWindow", "36"))
        self.casilla40.setText(_translate("MainWindow", "40"))
        self.casilla56.setText(_translate("MainWindow", "56"))
        self.casilla55.setText(_translate("MainWindow", "55"))
        self.casilla47.setText(_translate("MainWindow", "47"))
        self.casilla45.setText(_translate("MainWindow", "45"))
        self.casilla19.setText(_translate("MainWindow", "19"))
        self.casilla33.setText(_translate("MainWindow", "33"))
        self.casilla2.setText(_translate("MainWindow", "2"))
        self.casilla43.setText(_translate("MainWindow", "43"))
        self.casilla62.setText(_translate("MainWindow", "62"))
        self.casilla25.setText(_translate("MainWindow", "25"))
        self.casilla18.setText(_translate("MainWindow", "18"))
        self.casilla9.setText(_translate("MainWindow", "9"))
        self.casilla14.setText(_translate("MainWindow", "14"))
        self.casilla3.setText(_translate("MainWindow", "3"))
        self.casilla68.setText(_translate("MainWindow", "68"))
        self.casilla4.setText(_translate("MainWindow", "4"))
        self.casilla8.setText(_translate("MainWindow", "8"))
        self.casilla20.setText(_translate("MainWindow", "20"))
        self.casilla11.setText(_translate("MainWindow", "11"))
        self.casilla32.setText(_translate("MainWindow", "32"))
        self.casilla41.setText(_translate("MainWindow", "41"))
        self.casilla63.setText(_translate("MainWindow", "63"))
        self.casilla67.setText(_translate("MainWindow", "67"))
        self.casilla35.setText(_translate("MainWindow", "35"))
        self.casilla23.setText(_translate("MainWindow", "23"))
        self.casilla57.setText(_translate("MainWindow", "57"))
        self.casilla29.setText(_translate("MainWindow", "29"))
        self.casilla52.setText(_translate("MainWindow", "52"))
        self.casilla17.setText(_translate("MainWindow", "17"))
        self.casilla15.setText(_translate("MainWindow", "15"))
        self.casilla21.setText(_translate("MainWindow", "21"))
        self.casilla22.setText(_translate("MainWindow", "22"))
        self.casilla5.setText(_translate("MainWindow", "5"))
        self.casilla1.setText(_translate("MainWindow", "1"))
        self.casilla13.setText(_translate("MainWindow", "13"))
        self.casilla12.setText(_translate("MainWindow", "12"))
        self.casilla24.setText(_translate("MainWindow", "24"))
        self.casilla7.setText(_translate("MainWindow", "7"))
        self.casilla6.setText(_translate("MainWindow", "6"))
        self.casilla64.setText(_translate("MainWindow", "64"))
        self.casilla61.setText(_translate("MainWindow", "61"))
        self.casilla60.setText(_translate("MainWindow", "60"))
        self.casilla66.setText(_translate("MainWindow", "66"))
        self.casilla65.setText(_translate("MainWindow", "65"))
        self.casilla16.setText(_translate("MainWindow", "16"))
        self.casilla34.setText(_translate("MainWindow", "34"))
        self.casilla59.setText(_translate("MainWindow", "59"))
        self.casilla31.setText(_translate("MainWindow", "31"))
        self.casilla26.setText(_translate("MainWindow", "26"))
        self.casilla42.setText(_translate("MainWindow", "42"))
        self.casilla48.setText(_translate("MainWindow", "48"))
        self.casilla38.setText(_translate("MainWindow", "38"))
        self.casilla50.setText(_translate("MainWindow", "50"))
        self.casilla39.setText(_translate("MainWindow", "39"))
        self.btnLanzarDado.setText(_translate("MainWindow", "Lanzar dado"))
        self.label.setText(_translate("MainWindow", "Turno de : "))
