# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/oceanethomas/PycharmProjects/ParchisPreOfficial/numero_jugadores.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 665)
        MainWindow.setStyleSheet("background-color: #ADD8E6")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 621, 91))
        self.label.setMinimumSize(QtCore.QSize(8, 0))
        font = QtGui.QFont()
        font.setFamily("Chalkboard SE")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(210, 360, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("QPushButton {\n"
"    background-color: #1d5a96;\n"
"    color: black;\n"
"    font-size: 24px;\n"
"    border-radius: 40px;\n"
"    padding: 20px;\n"
"}")
        self.btn3.setObjectName("btn3")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(360, 180, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("QPushButton {\n"
"    background-color: #1d5a96;\n"
"    color: black;\n"
"    font-size: 24px;\n"
"    border-radius: 40px;\n"
"    padding: 20px;\n"
"}")
        self.btn2.setObjectName("btn2")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(510, 360, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("QPushButton {\n"
"    background-color: #1d5a96;\n"
"    color: black;\n"
"    font-size: 24px;\n"
"    border-radius: 40px;\n"
"    padding: 20px;\n"
"}")
        self.btn4.setObjectName("btn4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Número de jugadores"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn4.setText(_translate("MainWindow", "4"))
